name: WEB E2E Testes CI

on:
  workflow_dispatch:

jobs:
  web-test:
    runs-on: ubuntu-latest

    steps:
      #Clone do projeto na maquina
      - uses: actions/checkout@v4

      #Conferir a versão instalada
      - name: Node version
        run: node --version

      - name: Instalando dependencias
        run: npm install

      - name: Configurar ambiente para CI
        run: |
          echo '{"CAPTURE_SCREENSHOTS": false, "VIDEO_RECORDING": false, "ENABLE_PERFORMANCE_MODE": true}' > cypress.env.json

      - name: Verificar tamanho inicial
        run: npm run cy:size

      - name: Executando os testes (modo otimizado)
        run: npm run cy:run:headless
        continue-on-error: true

      - name: Limpeza pós-execução
        run: npm run cy:clean:force

      - name: Verificar tamanho final
        run: npm run cy:size

      - name: Upload artefatos (sempre)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-test-results-${{ github.run_number }}
          path: |
            cypress/screenshots/**/*
            cypress/reports/**/*
            cypress/videos/**/*
          retention-days: 30

      - name: Upload evidências de falha (apenas falhas)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-failure-evidence-${{ github.run_number }}
          path: |
            cypress/screenshots/**/*
            cypress/reports/**/*
          retention-days: 7
